- hosts: all 
  become: yes
  tasks:

#    - name: Install basic utils and build envs.
#      apt: pkg={{ item }} state=present
#      with_items:

    - name: Install required system packages.
      apt: pkg={{ item }} state=present
      with_items:
        - python-numpy 
        - python-scipy 
        - python-matplotlib
        - python-pandas         

    - name: Install Jupyter
      pip: name=jupyter
