- hosts: all
  vars:
    - package_names:
      - texlive-latex-base
      - texlive-latex-base-doc
      - texlive-latex-extra
      - texlive-latex-extra-doc
      - texlive-generic-extra
      - texlive-latex-recommended
      - texlive-latex-recommended-doc
      - texlive-science
      - texlive-fonts
      - texlive-fonts-extra
      - latexmk

  tasks:
    - name: install latex packages
      apt: pkg="{{item}}" state="present"
      with_items: "{{package_names}}"
      become: yes

    - name: install basics
      apt: pkg="{{item}}" state="present"
      with_items:
        - git
        - vim
        - build-essential
        - python-pip
      become: yes

    - name: Upgrade pip
      pip:
        name: pip
        extra_args: --upgrade
      become: yes

    - name: install pygments
      pip:
        name: pygments
      become: yes
