---
- hosts: localhost

  tasks:
    - name: Added mongodb key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5

    - name: Add mongodb repository
      become: yes
      apt_repository:
        repo: deb https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse
        state: present

    - name: Install mongodb
      become: yes
      apt:
        pkg: mongodb-org
        state: latest
        update_cache: yes
        cache_valid_time: 86400

    - name: ensure mongodb is running and starts on boot
      service: name=mongod state=restarted enabled=true
      become: yes

    - name: Installing Python-Pip
      apt:
        pkg: python-pip
        state: latest

    - name: Install the latest pymongo package
      pip: name=pymongo state=latest use_mirrors=no
