- hosts: all 
  become: yes
  tasks:

#    - name: Install basic utils and build envs.
#      apt: pkg={{ item }} state=present
#      with_items:

    - name: check python version
      command: python --version
      register: python_version

    - debug:
      msg: "Python Version output: {{python_version}}"

    - name: Install required system packages.
      apt: pkg={{ item }} state=present
      with_items:
        - python-numpy 
        - python-scipy 
        - python-matplotlib
        - python-pandas         
      when: python_version.stdout.startswith('Python 2') or python_version.stderr.startswith('Python 2')

    - name: Install Jupyter
      pip: name=jupyter
      when: python_version.stdout.startswith('Python 2') or python_version.stderr.startswith('Python 2')

    - name: Install required system packages.
      apt: pkg={{ item }} state=present
      with_items:
        - python3-numpy 
        - python3-scipy 
        - python3-matplotlib
        - python3-pandas         
      when: python_version.stdout.startswith('Python 3') or python_version.stderr.startswith('Python 3')

    - name: Install Jupyter
      pip: name=jupyter
      when: python_version.stdout.startswith('Python 3') or python_version.stderr.startswith('Python 3')
