- hosts: all 
  become: yes
  tasks:

    - name: Install basic utils and build envs.
      apt: pkg={{ item }} state=present
      with_items:
        - git
        - unzip
        - vim
        - build-essential

    - name: Install required system packages.
      apt: pkg={{ item }} state=present
      with_items:
        - python-dev
        - python-pip
        - python-setuptools

    - name: Upgrade pip
      pip:
        name: pip
        extra_args: --upgrade